AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Name:
    Type: String
    Description: name of the server
  KeyName:
    Description: https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#KeyPairs
    Type: AWS::EC2::KeyPair::KeyName
    Default: ssh
    NoEcho: true
    # TODO: regen with password, better name
  InstanceType:
    Description: https://aws.amazon.com/ec2/instance-types/
    Type: String
    Default: t3.small
  AMI:
    Type: AWS::EC2::Image::Id
  Subnet:
    Type: AWS::EC2::Subnet::Id
    Description: us-east-1c
    Default: subnet-08bcb7e889b485874
  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
  AMIDeviceMount:
    Type: String
    Description: aws ec2 describe-images --query "Images[0].RootDeviceName" --image-ids ami-XXXXXXXXXX
    Default: /dev/sda1
    # TODO: persisting the save file

Resources:
  # docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: game-server
      InstanceType: !Ref InstanceType # TODO: ssm /cfn/eco-instance-type
      PropagateTagsToVolumeOnCreation: True
      SecurityGroupIds: !Ref SecurityGroups
      KeyName: !Ref KeyName
      ImageId: !Ref AMI
      SubnetId: !Ref Subnet
      Tags:
        - Key: Name
          Value: !Ref Name

  # docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip-association.html
  EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: eipalloc-0524c5bad9df42cdb # TODO: ssm /cfn/eco-eip-id
      InstanceId: !Ref Instance

  # docs: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html
  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub ${Name}.coilysiren.me.
      HostedZoneName: coilysiren.me.
      TTL: 60
      Type: A
      ResourceRecords:
        # TODO: ssm /cfn/eco-epi-address
        - 3.225.219.68

  # # docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-ebs-volume.html
  # Volume:
  #   Type: AWS::EC2::Volume
  #   DeletionPolicy: Snapshot
  #   UpdateReplacePolicy: Snapshot
  #   Properties:
  #     Size: 10
  #     AvailabilityZone: !GetAtt Instance.AvailabilityZone
  #     Tags:
  #       - Key: Name
  #         Value: !Ref Name

  # # docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-ebs-volumeattachment.html
  # VolumeAttachment:
  #   Type: AWS::EC2::VolumeAttachment
  #   Properties:
  #     InstanceId: !Ref Instance
  #     VolumeId: !Ref Volume
  #     Device: !Ref AMIDeviceMount
