AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Name:
    Type: String
    Description: name of the server
    Default: eco-server
  KeyName:
    Description: https://us-east-1.console.aws.amazon.com/ec2/v2/home?region=us-east-1#KeyPairs
    Type: AWS::EC2::KeyPair::KeyName
    Default: ssh
  InstanceType:
    Description: https://aws.amazon.com/ec2/instance-types/
    Type: String
    Default: t2.nano
  SSHLocation:
    Description: curl ifconfig.me
    Type: String
    Default: 24.188.109.78/32
  AMI:
    Type: AWS::EC2::Image::Id
    Description: latest 64-bit (x86) ubuntu server here - https://us-east-1.console.aws.amazon.com/ec2/v2/home?region=us-east-1#AMICatalog
    Default: ami-052efd3df9dad4825

Resources:
  # docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: general ec2 security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: !Ref "SSHLocation"

  # docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroups: [!Ref SecurityGroup]
      KeyName: !Ref KeyName
      ImageId: !Ref AMI
      Tags:
        - Key: Name
          Value: !Ref Name

  # docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-ebs-volume.html
  Volume:
    Type: AWS::EC2::Volume
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      Size: 10
      AvailabilityZone: !GetAtt Instance.AvailabilityZone

  # docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-ebs-volumeattachment.html
  VolumeAttachment:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref Instance
      VolumeId: !Ref Volume
      Device: /dev/sdh

Outputs:
  InstancePublicDnsName:
    Value: !GetAtt [Instance, PublicDnsName]
    Description: DNS Name of the newly created EC2 instance
