AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Name:
    Type: String
    Description: name of the server

Resources:
  # docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-ebs-volume.html
  Volume:
    Type: AWS::EC2::Volume
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      Size: 10
      AvailabilityZone: us-east-1c
      Tags:
        - Key: Name
          Value: !Ref Name

  VolumeParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /cfn/${Name}/ebs-vol
      Type: String
      Value: !Ref Volume

Outputs:
  Volume:
    Value: !Ref Volume
